- title: "International Workshop on Search-Based Software Testing"
  categories: [workshop]
  date: '2022-01-01'
  date-format: YYYY
  description: "Program Committee Member"
  year-range: "2022 - 2008"
  service-count: 12
- title: "Testing: Academic and Industrial Conference &mdash; Practice and Research Techniques"
  categories: [conference]
  date: '2015-01-01'
  date-format: YYYY
  description: "Program Co-Chair, Program Committee Member"
  year-range: "2015 - 2007"
  service-count: 7
- title: "International Conference on Software Engineering"
  categories: [conference]
  date: '2022-01-01'
  date-format: YYYY
  description: "Program Committee Member, Reviewer"
  year-range: "2022 - 2005"
  service-count: 4
- title: "International Conference on the Foundations of Software Engineering"
  categories: [conference]
  date: '2005-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2005"
  service-count: 1
- title: "International Symposium on Applied Computing"
  categories: [conference]
  date: '2009-01-01'
  date-format: YYYY
  description: "Session Chair, Reviewer"
  year-range: "2009 - 2004"
  service-count: 2
- title: "International Conference on Distributed Computing Systems"
  categories: [conference]
  date: '2003-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2003"
  service-count: 2
- title: "PeerJ Computer Science Journal"
  categories: [journal]
  date: '2023-01-01'
  date-format: YYYY
  description: "Academic Editor"
  year-range: "2023 - 2019"
  service-count: 3
- title: "Genetic Programming and Evolvable Machines Journal"
  categories: [journal]
  date: '2020-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2020"
  service-count: 1
- title: "Formal Aspects of Computing Journal"
  categories: [journal]
  date: '2018-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2018"
  service-count: 1
- title: "IET Software Journal"
  categories: [journal]
  date: '2019-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2019 - 2018"
  service-count: 4
- title: "Transactions on Services Computing"
  categories: [journal]
  date: '2018-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2018 - 2017"
  service-count: 2
- title: "Transactions on Industrial Informatics"
  categories: [journal]
  date: '2017-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2017"
  service-count: 1
- title: "Software and Systems Modelling Journal"
  categories: [journal]
  date: '2016-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2016"
  service-count: 1
- title: "IEEE Software Journal"
  categories: [journal]
  date: '2015-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2015"
  service-count: 1
- title: "Empirical Software Engineering Journal"
  categories: [journal]
  date: '2020-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2020 - 2012"
  service-count: 4
- title: "Advances in Software Engineering Journal"
  categories: [journal]
  date: '2010-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2010"
  service-count: 1
- title: "Journal of Software Engineering and Knowledge Engineering"
  categories: [journal]
  date: '2010-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2010"
  service-count: 1
- title: "Journal of Software Testing Verification and Reliability"
  categories: [journal]
  date: '2021-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2021 - 2009"
  service-count: 13
- title: "Journal of Software Systems and Software"
  categories: [journal]
  date: '2020-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2020 - 2009"
  service-count: 14
- title: "Software Quality Journal"
  categories: [journal]
  date: '2020-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2021 - 2009"
  service-count: 16
- title: "Information and Software Technology"
  categories: [journal]
  date: '2023-01-01'
  date-format: YYYY
  description: "Reviewer"
  year-range: "2023 - 2009"
  service-count: 13
